### ISSUE TITLE
Crashes when identifying a large # of images in bulk

### ISSUE THREAD

**Issue by xjdeng** [TensorPy/TensorPy#12]
I'm not sure if this is a problem with TesnorPy, Tensorflow, or the Windows 10 Linux Subsystem, but I've created the following script to bulk classify images in a directory and then output a dictionary indicating the # of times each classification is found.  Here's my code:

```
from tensorpy import classify_image
from path import Path as path
from tensorflow.python.framework.errors_impl import InvalidArgumentError

def dir_classify(dirstr):
	mydir = path(dirstr)
	classes = {}
	for f in mydir.files():
		try:
			guess = classify_image.external_run(f)
			if guess in classes:
				classes[guess] += 1
			else:
				classes[guess] = 1
		except InvalidArgumentError:
			pass
	return classes
```

Note you need to install path.py to run this:
```
pip install path.py
```

Here's the info on my environment:

Python version: 2.7.13 (Anaconda 4.3.1)
OS: Windows 10 (but running the Linux Subsystem)

To reproduce this error, run the above like the following:

```
dir_classify("/mnt/c/pictures")
```
(Assuming you've got a bunch of pictures in c:\pictures)

When I run this on a Windows machine using the Linux Subsystem, it freezes my entire machine.  The screen turns off and my machine stops responding to any keyboard or mouse input.

I then tried running it on a native Linux installation (Linux Mint 18.1 to be precise) and it doesn't completely freeze my computer but it exists with the error "Killed"..  it doesn't even throw an exception, just throws you out of Python.

**Comment by mdmintz** [comment]
Hello,

First, I'm assuming you're able to run a basic classify command such as the following from your command line (which verifies that installation was successful):
`classify https://github.com/TensorPy/TensorPy/blob/master/examples/images/bird_animal.jpg`

If you're trying to classify multiple images from a folder on your file system, you may want to try a bash script like:
```
for i in temp_image_folder/*.jpg; do
    python classify_image.py --image=$i
done
```
(...which assumes you've created a folder called temp_image_folder in the tensorpy folder which contains classify_image.py, and that you've added images to that folder. The `--image=[IMAGE.jpg]` is for classifying images held on your file system. )

If you're running into Windows-specific issues, I'd strongly suggest trying the Docker TensorPy tutorial, found in the ReadMe here: https://github.com/TensorPy/TensorPy/tree/master/third_party/docker ...which is what I used when testing TensorPy on a Windows machine. Otherwise I'm using the unix file system on my Mac OS-X.

**Comment by xjdeng** [comment]
Yeah, the basic classify command works from the command line.

But what I'm more interested in is running this on a large # of files and returning the result in the form of a Python dictionary.  I can't find an efficient way to do that without the program crashing.  Or am I supposed to call your script using os.system() in my Python program and extract the result?

**Comment by mdmintz** [comment]
Hi @xjdeng ,
I've just made some changes to TensorPy to make what you want possible.
Here are two new recently-merged pull requests:
https://github.com/TensorPy/TensorPy/pull/13/files
https://github.com/TensorPy/TensorPy/pull/14/files

Here's the test that classifies all images in a folder into a dict:
https://github.com/TensorPy/TensorPy/blob/master/examples/test_python_folder_classify_dict.py

Here's the output:
```
python test_python_folder_classify_dict.py 
All classifications have been completed!
*** Displaying Image Classification Results as dictionary: ***
{'water_animal.jpg': 'tiger shark', 'bird_animal.jpg': 'flamingo', 'happy_animal.jpg': 'giant panda', 'cat_animal.jpg': 'snow leopard', 'reptile_animal.jpg': 'African chameleon'}
```

**Comment by mdmintz** [comment]
Hi @xjdeng ,
The latest version of TensorPy, 1.0.17 (just released), should answer any of your remaining questions. See the updated ReadMe for the new examples: https://github.com/TensorPy/TensorPy/blob/master/README.md

**Comment by xjdeng** [comment]
Thank you so much!
