### ISSUE TITLE
`classify` command downloads to a .png and then fails to convert the image

### ISSUE THREAD

**Issue by trejkaz** [TensorPy/TensorPy#17]
For any URL I have tried so far, I get the following outcome:

```
$ classify 'http://www.kitchengoodies.ca/uploads/ecom/fullsize/Lecreuset%20Stainless%20Kettle.jpg'
Traceback (most recent call last):
  File "/usr/local/bin/classify", line 11, in <module>
    load_entry_point('tensorpy==1.0.17', 'console_scripts', 'classify')()
  File "build/bdist.macosx-10.12-x86_64/egg/tensorpy/classify.py", line 91, in main
  File "build/bdist.macosx-10.12-x86_64/egg/tensorpy/image_base.py", line 90, in classify_image_url
  File "build/bdist.macosx-10.12-x86_64/egg/tensorpy/image_base.py", line 31, in convert_image_file_to_jpg
Exception: Cannot convert downloads_folder/temp_image_c614d6edb49b4cbe995bbf71bca1c780.png to jpg!
```

The comedy gold here is that the image was _already_ a JPG, but somehow classify has saved it in a file ending in '.png', and is now wondering why it fails to convert this to JPEG. 🤣 

(The `classify_image.py` script which operates on local files works totally fine, of course.)

**Comment by mdmintz** [comment]
Thank you @trejkaz for catching that! I have made changes to fix that: https://github.com/TensorPy/TensorPy/pull/18
The issue was with using the latest version of Pillow (the Python Imaging Library) due to what seems to be a bug there. In my requirements.txt and setup.py files, I previously had "Pillow>=4.1.1", which automatically installed a later version of Pillow if available, which was 4.2.1. I changed that to "Pillow==4.1.1", using == instead of >=, which now locks down the version to a working one. I also locked down the other dependency versions in case a future change to those breaks TensorPy as well. Please rerun "./install.sh" and let me know if that fixes everything for you. Thank you!
