### ISSUE TITLE
Realtime detection

### ISSUE THREAD

**Issue by Zumbalamambo** [TensorPy/TensorPy#19]
How do I detect objects in realtime using webcam?

**Comment by mdmintz** [comment]
Hi, @Zumbalamambo. First you'll need software that automatically saves still images from your webcam to a folder on your computer at regular intervals (I'm not sure which software is best for that at this time). Once you've done that, you can create a script that loops TensorPy's "classify" command to classify the still images from that folder and then save the results to some file.

**Comment by Zumbalamambo** [comment]
is it possible to convert tensorpy into a complete windows desktop app?

**Comment by mdmintz** [comment]
For now, if you want to run TensorPy on a Windows machine, you'll need to use Docker. (See the TensorPy Docker tutorial: https://github.com/TensorPy/TensorPy/blob/master/third_party/docker/ReadMe.md). You should be able to bundle everything into your Docker instance.
The main reason for this is because Python 3 is required for installing/running TensorFlow on Windows natively (as seen from the TensorFlow installation instructions: https://www.tensorflow.org/install/install_windows#installing_with_native_pip), and right now TensorPy is built in Python 2. I was hoping that the creators of TensorFlow would add the ability to use TensorFlow on Windows natively with Python 2, but seems unlikely at this time. The workaround would require me to rewrite all of TensorPy in Python 3 in the future, which I may do, but it might not happen anytime soon. Try using the TensorPy Docker instructions as the basis of your standalone Windows desktop app.

**Comment by mdmintz** [comment]
@Zumbalamambo, Try this tutorial: https://codelabs.developers.google.com/codelabs/nest-camera-api/index.html?index=..%2F..%2Findex#0

**Comment by mdmintz** [comment]
@Zumbalamambo If it helps, TensorPy now supports Python 3.
